### ISSUE TITLE
Need a way to add scraped info as a feature (ex. Category) 

### ISSUE THREAD

**Issue by mindyh** [bhnascar/Viral-Art#1]

**Comment by mindyh** [comment]
Other metadata we may want as features:

- traditional vs. digital
- how many watchers the author has(? if it's easy to do)

**Comment by bhnascar** [comment]
Hm, I want to make a distinction between "features" and outputs...I think we can certainly add other metadata, but not as "features", but as other things to predict. I think the features should be strictly stuff that we compute based on the image alone.

**Comment by mindyh** [comment]
Disagree - First, it'd be interesting to know which mediums and categories garner the most popularity (since we're restricted to portraiture, the will only be a distinction between Fan Art and Not Fan Art).  Second, sure, more watchers means more views, but not necessarily a high favorite:view ratio.

**Comment by mindyh** [comment]
I was thinking maybe we should make the view:favorite ratio our final metric, but that really messes up when the image only has 3 views and 1 favorite, so I think it's best to keep them separate for purposes of prediction and then compute the ratio at the end, to make the information more revealing.

**Comment by mindyh** [comment]
Also - while views are generally correlated with number of watchers it's definitely not the only factor. Ex. I just looked an artist with 1k views on their work and only 100 watchers, and another with 4,000 watchers but only 2k views. I also know people with >100 watchers but less than 100 views on their works, and people with < 20 watchers but several hundred views. It's not hard to find examples like these. So I think adding watchers as a feature would be much more informative than destructive (give us a more accurate model, and tell us how much having watchers actually affects your view/fav counts)

**Comment by bhnascar** [comment]
Alright that sounds good haha. Pretty thorough argument you made there.

**Comment by bhnascar** [comment]
Okay wait hold up, getting the view count is going to be an issue. Because I'm assuming we're not scraping everything in one go, we'll be adding more image as we need. Which means that we'll have to find some way to "normalize" view count since older images should have more views.

Or, we could try to work around this issue by only looking at old images, period. I.e. stuff from three-four years back that have been seen and done (do image view counts stabilize over time - I don't use DeviantArt enough to know this).

**Comment by bhnascar** [comment]
How many images do you think we're going to need? Would it suffice to, say, scrape one month's worth of portraits and just stick to that?

**Comment by mindyh** [comment]
We can start with one month's. Honestly view counts settle within the first
weeks, depending on how popular the artist is. If we scrape things from a
year back we should be pretty safe.

**Comment by bhnascar** [comment]
Where can I find traditional vs. digital information? Ex: [http://elenasai.deviantart.com/art/s-lebovsky-608968045](http://elenasai.deviantart.com/art/s-lebovsky-608968045)

In the navigation crumb? I.e. Digital Art / Drawings & Paintings / People / Portraits

What about # of watchers?

**Comment by mindyh** [comment]
Yea, the navigation is the only way to do it. We have to rely on the artist
to self report essentially.
# watchers can only be found on the artists profile page, which us why I
said only do it if it's not too hard

**Comment by bhnascar** [comment]
Okay yeah I can maybe spend an hour on this tonight. So the issue with watchers is that even under the artists profile page, there's no single place that says there's "X" number of watchers. There's the "See all watchers" tab which just gives you a list...but that list only shows the top 100, and then you can click "See more", but it looks like you can't find out how many there are in total except by clicking "See more" until you can't go any further.

**Comment by mindyh** [comment]
There is, it's under a profile or info button at the top of their page.
I'll send you a screenshot of you still can't find it. Sorry I'm out for
the next few hours

**Comment by bhnascar** [comment]
Ah, I found it yeah it's under a drop menu so not very visible.

**Comment by bhnascar** [comment]
Okay, update: watchers is no-go, sorry. It turns out that information is not actually in the page source, but dynamically generated via Javascript, which means I can't scrape it. Unless I find a scraping library with a full rendering engine that can exectue Javascript, and I'm already pretty far along with BeautifulSoup, so I don't want to switch.

**Comment by mindyh** [comment]
Yeah no problem on that. I figured that feature would be a stretch to get
anyways. We definitely have better things to do with our time
