### ISSUE TITLE
handle if feature value returns None

### ISSUE THREAD

**Issue by mindyh** [bhnascar/Viral-Art#16]
- Write it to database correctly
- When reading features from database, if it's None then don't add it to the features list

**Comment by bhnascar** [comment]
Okay, so now I've split the functionality into three modules. 

To extract stuff:
`./extractor.py`

To dump features from DB into a text file:
`./dumper.py`

And these things have optional arguments that you can use to customize their behavior (for example, dump only specific columns into your feature output file, update only specific columns in the database...)
