### ISSUE TITLE
Image segmentation

### ISSUE THREAD

**Issue by bhnascar** [bhnascar/Viral-Art#31]
I've got some ideas on how to do this to analyze composition....basically, do mean-shift, take the biggest chunks and average out their horizontal and vertical positions for every horizontal/vertical scanline, and express that as a fraction of the height or width of the image. Thoughts?

**Comment by mindyh** [comment]
SGTM. I'm already doing something like this for the face. The only hard part is thinking about how to represent each chunk as a separate feature in a way that makes sense and we can train weights on it.

**Comment by bhnascar** [comment]
Okay, currently working on using image segmentation for highlights instead...not super promising
