### ISSUE TITLE
extractor.py: IO error 

### ISSUE THREAD

**Issue by mindyh** [bhnascar/Viral-Art#39]
![capture](https://cloud.githubusercontent.com/assets/2425772/15552184/26fdd1aa-226e-11e6-9dbc-655e91b86fe0.PNG)

**Comment by bhnascar** [comment]
Whoops, do you have a workspace folder? Can you try adding one to your project directory. I have one but I put it in the git ignore, because it's the place where I dump temp images and it made no sense to throw that up on git.

**Comment by mindyh** [comment]
Easy fix, sounds good.
