### ISSUE TITLE
dumper.py doesn't dump out column names

### ISSUE THREAD

**Issue by mindyh** [bhnascar/Viral-Art#40]

**Comment by mindyh** [comment]
I see the code that says it does, but when I run it it doesn't...

**Comment by mindyh** [comment]
ok I see, it doesn't write the headers if the file already exists...but what if we need to rewrite the headers because we added more features? I commented it out for now as I'm working, lmk what you think.

**Comment by bhnascar** [comment]
Whoops yeah if the file exists it keeps adding to the end of the file. My idea was that you might have added more database rows and you wanted to export the new stuff. Will fix this soon..
