### ISSUE TITLE
Write scraper for DA

### ISSUE THREAD

**Issue by mindyh** [bhnascar/Viral-Art#5]
1.     Get URL for images
2.     Given URL for image, get the
  -  image
  - views
  - favs
  - category
  - number of watchers the artist has

**Comment by bhnascar** [comment]
Currently looking into https://www.crummy.com/software/BeautifulSoup/bs4/doc/

**Comment by bhnascar** [comment]
Is this an appropriate RSS link?  

http://backend.deviantart.com/rss.xml?q=boost%3Apopular+in%3Adigitalart%2Fpaintings%2Fpeople%2Fportraits+max_age%3A24h&type=deviation

**Comment by bhnascar** [comment]
Nope, nvm, doesn't have fav or views data.

**Comment by bhnascar** [comment]
Okay we now have a scraper. Yay!

You can use it to scrape a search results page like so:

This will add every single image in the search results to our database, including favorites, view count, medium, and url to the actual image.

`./scraper.py -r http://www.deviantart.com/browse/all/digitalart/paintings/people/portraits/`

You can also scrape a single image page and add only data for that image to our database, like so:

`./scraper.py -s http://www.deviantart.com/art/Reds-606604260`

Note that this doesn't automatically run the feature extractor over the images. You'd still have to call `./extractor.py` to actually run all the image analysis stuff.

**Comment by mindyh** [comment]
Wow, so fast. How long does it take to scrape an image? And just making
sure, you put a delay in right, I don't want to get banned >.<
