### ISSUE TITLE
Add Favorites, Views of the image column into the Database 

### ISSUE THREAD

**Issue by mindyh** [bhnascar/Viral-Art#9]

**Comment by bhnascar** [comment]
Just to clarify, is this going to be our ground truth comparison? I.e. our regressor will be trying to predict favorites slash view count within some ballpark of the actual value?

**Comment by mindyh** [comment]
Yep. Need to think about if we're going to predict views/favorites together or separately. I think separately would be easier and more enlightening (not everything that looks intriguing as a thumbnail gets favorited)
